import {
  Plus,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  SearchIcon,
  XIcon,
  CheckIcon,
  CircleIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  MoreHorizontalIcon,
  Check,
  RotateCcw as Reset,
  House,
  ArrowBigLeft,
  Search,
  Bell,
  Home,
  Users,
  Calendar,
  ClipboardList,
  FolderOpen,
  MessageSquare,
  Brain,
  Eye,
  X,
  Tag,
  Pen,
  ImageIcon,
  Trash2 as Trash,
  Star,
  UserIcon,
  CircleX as tempIcon,
  GraduationCap as StudentIcon,
  BookOpen as TeacherIcon,
  Clock,
  FileText as File,
  Link,
} from "lucide-react";
import { cn } from "@/lib/utils.ts";

export let iconLibrary = {
  Plus: wrapIcon(Plus),
  ChevronUp: wrapIcon(ChevronUp),
  ChevronDown: wrapIcon(ChevronDown),
  TempIcon: wrapIcon(tempIcon),
  ChevronLeft: wrapIcon(ChevronLeft),
  ChevronRight: wrapIcon(ChevronRight),
  SearchIcon: wrapIcon(SearchIcon),
  XIcon: wrapIcon(XIcon),
  CheckIcon: wrapIcon(CheckIcon),
  ChevronRightIcon: wrapIcon(ChevronRightIcon),
  CircleIcon: wrapIcon(CircleIcon),
  MoreHorizontalIcon: wrapIcon(MoreHorizontalIcon),
  ChevronLeftIcon: wrapIcon(ChevronLeftIcon),
  CircleX: wrapIcon(tempIcon),
  ChevronDownIcon: wrapIcon(ChevronDownIcon),
  ChevronUpIcon: wrapIcon(ChevronUpIcon),
  Check: wrapIcon(Check),
  Reset: wrapIcon(Reset),
  House: wrapIcon(House),
  ArrowBigLeft: wrapIcon(ArrowBigLeft),
  Search: wrapIcon(Search),
  Bell: wrapIcon(Bell),
  Home: wrapIcon(Home),
  Users: wrapIcon(Users),
  Calendar: wrapIcon(Calendar),
  ClipboardList: wrapIcon(ClipboardList),
  FolderOpen: wrapIcon(FolderOpen),
  MessageSquare: wrapIcon(MessageSquare),
  Brain: wrapIcon(Brain),
  Eye: wrapIcon(Eye),
  Star: wrapIcon(Star),
  X: wrapIcon(X),
  UserIcon: wrapIcon(UserIcon),
  StudentIcon: wrapIcon(StudentIcon),
  TeacherIcon: wrapIcon(TeacherIcon),
  Trash: wrapIcon(Trash),
  Tag: wrapIcon(Tag),
  Pen: wrapIcon(Pen),
  ImageIcon: wrapIcon(ImageIcon),
  Clock: wrapIcon(Clock),
  File: wrapIcon(File),
  Link: wrapIcon(Link),
};

function wrapIcon(Icon: React.ComponentType<any>, defaultClass = "size-4") {
  return ({ className, ...props }: React.ComponentProps<typeof Icon>) => (
    <Icon className={cn(defaultClass, className)} {...props} />
  );
}
